-- SERVICE_DYN_UMB_HEADER definition

-- Drop table

-- DROP TABLE SERVICE_DYN_UMB_HEADER;

CREATE TABLE SERVICE_DYN_UMB_HEADER (
	MENU_ID varchar NULL,
	MENU_HEADER varchar NULL,
	PACKAGE_FLAG varchar NULL,
	PACKAGE_SEQUENCE varchar NULL,
	PACKAGE_PERIOD varchar NULL,
	PACKAGE_CODE varchar NULL,
	DAYS_CATEGORY varchar NULL,
	KEYWORD varchar NULL,
	SHORTCODE varchar NULL,
	REG_AMOUNT varchar NULL,
	PACKAGE_DESCRIPTION varchar NULL,
	UNIT varchar NULL,
	FORMULA varchar NULL,
	PROMO_PACKAGE_CODE varchar NULL,
	"PARAMETER" varchar NULL,
	BENEFIT_1 varchar NULL,
	BENEFIT_2 varchar NULL,
	BENEFIT_3 varchar NULL,
	BENEFIT_4 varchar NULL,
	BENEFIT_5 varchar NULL,
	CUSTOMER_TYPE varchar NULL,
	CUSTOM_FLAG varchar NULL
);


-- SERVICE_DYN_UMB_MENU definition

-- Drop table

-- DROP TABLE SERVICE_DYN_UMB_MENU;

CREATE TABLE SERVICE_DYN_UMB_MENU (
	MENU_ID varchar NULL,
	MENU_NEXT_ID varchar NULL,
	MENU_DETAIL_ITEM varchar NULL,
	PACKAGE_FLAG varchar NULL,
	PACKAGE_SEQUENCE varchar NULL,
	PACKAGE_PERIOD varchar NULL,
	PACKAGE_CODE varchar NULL,
	DAYS_CATEGORY varchar NULL,
	KEYWORD varchar NULL,
	SHORTCODE varchar NULL,
	REG_AMOUNT varchar NULL,
	PACKAGE_DESCRIPTION varchar NULL,
	ITEM_NUMBER varchar NULL,
	FORMULA varchar NULL,
	UNIT varchar NULL,
	PACKAGE_FLAG_ID varchar NULL,
	BENEFIT_1 varchar NULL,
	BENEFIT_2 varchar NULL,
	BENEFIT_3 varchar NULL,
	BENEFIT_4 varchar NULL,
	BENEFIT_5 varchar NULL,
	CUSTOM_FLAG varchar NULL
);